# Use Ubuntu 14.04
sudo: required
dist: trusty

# Set the language
language: cpp

# Set the compiler
compiler:
    - gcc


# Install build packages
install:
    # Check if cmake is installed and, if not, installs it
    - $(which cmake > /dev/null) || (sudo apt-get update && sudo apt-get install cmake) && echo "cmake installed"
#      # Install ROOT from the CERN website
#    - bash travisCI/install-root.sh
#    - . ./root/bin/thisroot.sh
#    - bash travisCI/install-bat.sh
#      # Set the BAT environment
#    - export PATH="/home/travis/build/pdigiglio/YAP/bat/bin:$PATH"
#    - export LD_LIBRARY_PATH="/home/travis/build/pdigiglio/YAP/bat/lib:$LD_LIBRARY_PATH"
#    - export CPATH="/home/travis/build/pdigiglio/YAP/bat/include:$CPATH"
#    - export PKG_CONFIG_PATH="/home/travis/build/pdigiglio/YAP/bat/lib/pkgconfig:$PKG_CONFIG_PATH"
#      # Set $YAPDIR
#    - export YAPDIR="$PWD"

# Build
script:
    - mkdir build && cd build
    - cmake .. && make -j test && ./test/test
